# Generated by Django 4.1 on 2022-09-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
