# Generated by Django 4.1 on 2022-09-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_projects_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('skill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.skill_category')),
            ],
        ),
    ]
