# Generated by Django 4.1 on 2022-08-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=100)),
                ('prod_quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
